name: MatchMaker
description: Réseau social lucratif Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  http: ^1.2.1
  intl: any
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/